[features]
seeds = false
skip-lint = false

[programs.localnet]
racers_vault = "RacersFun1111111111111111111111111111111111"

[programs.devnet]
racers_vault = "RacersFun1111111111111111111111111111111111"

[programs.mainnet]
racers_vault = "RacersFun1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[[test.validator]]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "11111111111111111111111111111111"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112"

[[test.validator.clone]]
address = "SysvarRent111111111111111111111111111111111"

[[test.validator.clone]]
address = "SysvarC1ock11111111111111111111111111111111"
